/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * guiEvaluacion.java
 *
 * Created on 25-feb-2013, 10:14:09
 */

package InterfazUsuario;
import EvaEmocion.marcoEmociones;

/**
 *
 * @author Omar
 */
public class guiEvaluacion extends javax.swing.JFrame {

    /** Creates new form guiEvaluacion */
    public guiEvaluacion() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboEmociones = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        salirEva = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));

        comboEmociones.setForeground(new java.awt.Color(0, 51, 153));
        comboEmociones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sorpresa", "Excitacion", "Euforia", "Alegria", "Satisfaccion", "Serenidad", "Relajamiento", "Tranquilidad", "Fatiga", "Aletargamiento", "Depresion", "Tristeza", "Dolencia", "Estres", "Enojo", "Miedo" }));
        comboEmociones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                almacenaEmocion(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Selecciona una emoción:");

        salirEva.setBackground(new java.awt.Color(0, 102, 204));
        salirEva.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        salirEva.setForeground(new java.awt.Color(0, 102, 204));
        salirEva.setText("Salir");
        salirEva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirEvalaucion(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(33, 33, 33)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(comboEmociones, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 84, Short.MAX_VALUE)
                        .add(salirEva)
                        .add(56, 56, 56))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(68, 68, 68)
                .add(jLabel1)
                .add(28, 28, 28)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(comboEmociones, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(salirEva))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void almacenaEmocion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_almacenaEmocion
        // TODO add your handling code here:
        nombreOpusPrim = guiSelector.comboOP.getSelectedItem().toString();
        emocion = comboEmociones.getSelectedItem().toString();
        System.out.println(nombreOpusPrim + " " + emocion);
        me = new marcoEmociones();
        me.setVisible(true);
    }//GEN-LAST:event_almacenaEmocion

    private void salirEvalaucion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirEvalaucion
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_salirEvalaucion

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guiEvaluacion().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox comboEmociones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton salirEva;
    // End of variables declaration//GEN-END:variables
    marcoEmociones me;
    String nombreOpusPrim, emocion;
}
